name: Build & Deploy Spring app

on:
    push:
        branches: [ "master" ]
    pull_request:
        branches: [ "master" ]

jobs:
    build-deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Set up JDK 17
              uses: actions/setup-java@v3
              with:
                  java-version: '17'
                  distribution: 'temurin'
                  cache: maven

            - name: Unit Tests
              run: mvn -B test --file pom.xml

            - name: Build with Maven
              run: |
                  mvn -B clean
                  mvn -B package --file pom.xml

            - name: BUild docker image
              uses: docker/build-push-action@v2
              with:
                  context: .
                  file: Dockerfile
                  push: false
                  tags: ${{secrets.DOCKER_HUB_ACCESS_USERNAME}}/cicd_example:$(date-'%Y-%m-%d
